# source: https://rfortherestofus.com/2023/05/github-actions

name: Process Data
# This action pulls data from Azure blob storage
# uses R to filter the data
# and then uploads the data back to an azure blob
# the action runs weekly on a schedule


# run the job at a scheduled time
on:
  push:
    branches: main
# This is 9 AM UTC which should correspond to 2 am in Seattle
# more deets about cron scheduling:
         # https://www.tinybird.co/docs/guides/ingest/scheduling-with-github-actions-and-cron
         # https://medium.com/tradeling/how-to-schedule-jobs-using-github-actions-9f32667706ea
  schedule:
  - cron: "0 9 * * 0"

jobs:
  fetch-from-API:

  # This step specifies which operating system environment you want to use
  # could be windows, linux or mac. Linux is usually the cheapest to run
  # You can also specify which version you want. In this case we're using the latest
    runs-on: ubuntu-latest
    steps:
      # This step installs R and its depencies onto the ubuntu virtual machine
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # On linux, R doesn't always install all the dependencies a package needs
      # So this step installs extra dependencies for some R packages that need them
      # I believe these are mostly for sf and other spatial packages
      - name: Install R package linux dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev

     # This loads all the repositories code onto the virtual machine
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run R script
        env: 
        # These are secrets we want loaded in as environmental variables
        # Theses three are all azure blob variables
          AZURE_KEY: ${{ secrets.AZURE_KEY }}
          BLOB_URL: ${{ secrets.BLOB_URL }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

        # This line runs an R script that's stored on the repo
        # you use the relative path starting at the repo level
        run: Rscript -e 'source("R/process_data/scripts/process_wolf_data.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . 
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
